### PR TITLE
#27 add bulkhead

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by johnament** [comment]
We need to define scoping within bulkhead.  E.g. if I have a request scoped component, am I counting the invocations across all threads (to different instances) of that component? Or is it only when its the same instance across multiple threads?

**Comment by Emily-Jiang** [comment]
I think we should spec counting the multiple threads per instance. There is no bulkhead in failsafe. Not sure how Hystrix counts the threads. I thought it might just count per instance not per class. Perhaps @antoinesd can confirm.

**Comment by Emily-Jiang** [comment]
I'm going to merge in. Please open issue if you have more thoughts on this.

**Comment by johnament** [comment]
I'll start to work on the spec tomorrow.

**Pull request merged**
