### PR TITLE
#4 add fallback

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Anyway we can make this type safe so it isn't a String?

Maybe Method instead?

**Comment by Emily-Jiang** [comment]
As for the return type, only primitive type, String, Class, annotation, enumeration are permitted. Reflection will be used to work out the method. By the way, Hystrix uses the similar approach.

**Comment by kenfinnigan** [comment]
Maybe a different approach then?

Fallback being a handler [1] that is then specified in the annotation [2]. Brings type safety to the problem without much effort, and fallbacks can be re-used where it makes sense.

[1] - https://github.com/kenfinnigan/wildfly-swarm-helloworld/blob/master/chaining/hola/src/main/java/org/wildfly/swarm/helloworld/chaining/hola/OlaFallbackHandler.java#L29
[2] - https://github.com/kenfinnigan/wildfly-swarm-helloworld/blob/master/chaining/hola/src/main/java/org/wildfly/swarm/helloworld/chaining/hola/OlaService.java#L40

**Comment by Emily-Jiang** [comment]
Not sure the handler approach is suitable for the annotation. Here is an example of Spring boot with Hystrix:
@RestController
public class NodeAController {
		 
		 @GetMapping("NodeA")
		 @HystrixCommand(fallbackMethod="fallback" )
		 public String makeCallToNodeB() throws Exception{
		 		 return new RestTemplate()
		 		 		 		 .getForEntity(new URI("http://localhost:8081/NodeB"), String.class)
		 		 		 		 .getBody();
		 }
		 
		 public String fallback(){
		 		 return "Red alert! This String is returned by the fallback method";
		 }
}
It is very similar to the current approach.

**Comment by kenfinnigan** [comment]
Can you elaborate on why you think the handler approach isn't suitable, as I thought the examples I provided showed it was?

Isn't it best to take advantage of type safety wherever we can?

I'd also prefer to not just copy how Spring Boot does things without thinking about alternatives

**Comment by Emily-Jiang** [comment]
I did not copying from anywhere and it is quite easy and natural thing to come up. After your comments, I looked further on Hystrix and try to understand your use case. Since Spring boot uses Hystrix, I thought to mention it here about its annotation support. 

As for this fallback annotation, in this case, the return type can either be a string or a class. If you looked at the 1st commit, it was a Class and then I thought it is much easier to use if the return type is String. If we all think returning a class is better. We can spec the fallback method in the class needs to have the exactly same method signature as the main service, which is workable. 

I might have misunderstood your handler idea. The return type cannot be anything more concrete than a class though.

**Comment by Emily-Jiang** [comment]
Maybe using CDI event is a better approach. When max retries reached, circuit open, no others things to do, execution failure should trigger a Fallback event to fire, so that the applications can observe the event and fallback. A PR to follow to demonstrate this idea.

**Comment by johnament** [comment]
When we spoke about fallbacks in the past, they were another implementation of the given class, which matched method signatures.  The string value would only be used if the method name was different.

**Comment by Emily-Jiang** [comment]
See https://github.com/eclipse/microprofile-fault-tolerance/pull/23

**Comment by Emily-Jiang** [comment]
Usage:
`public class MyFTService  {
 
    /**
     * @Todo test the asynchronous behaviour
     * 
     */
    
    public void serviceA() {
        
        serviceB();
    }
    
    @Retry
    @Fallback(handler=MyFallBackHandler.class)
    public void serviceB() {
        //remote call
    }
    
}

public class MyFallBackHandler implements FallbackHandler
{

    @Override
    public void handle(ExecutionContext context)
    {
         ...
        System.out.println(context.getMethod());
        System.out.println(context.getParameters());

    }

}

`

**Comment by Emily-Jiang** [comment]
see #24

**Pull request closed without merging**
