### PR TITLE
#409 fix thread ordering in BulkheadAsynchRetryTest.testRetriesJoinBackOfQueue

### PR DESCRIPTION
**Pull request by Ladicek**
Signed-off-by: Ladislav Thon <lthon@redhat.com>

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by Ladicek** [comment]
I just signed the ECA. How to retrigger the validation?

**Comment by Azquelt** [comment]
@genie-microprofile test this please

**Comment by Ladicek** [comment]
I don't know what else to do. The ECA validation tool tells me "There is a valid ECA on file for lthon@redhat.com", I even set the GitHub ID in my account settings.

**Comment by Azquelt** [comment]
I've manually verified that that you've signed an ECA.

**Comment by Ladicek** [comment]
Thank you!

**Pull request merged**
