### PR TITLE
Formatting fixes in "Asynchronous" section

### PR DESCRIPTION
**Pull request by TomasHofman**

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by Emily-Jiang** [comment]
@TomasHofman you need to sign your PR?

**Comment by TomasHofman** [comment]
@Emily-Jiang ok, I suppose that means signing the agreement on the Eclipse website and adding signed-off header. Should be fixed now.

**Comment by Azquelt** [comment]
@genie-microprofile test this please

**Pull request merged**
