### PR TITLE
#4 add event model to enable the exception recovery e.g. fallback

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Do you have an example of how this would be used by a developer?

**Comment by Emily-Jiang** [comment]
Here is the code snippet:
`public class TestFallback
{

    
    public void serviceA() {
        serviceB();
    }
    // An event will be fired if the circuit is open or max retry exceeded
    @CircuitBreaker
    public void serviceB() {
        
        //call a remote service 
    }
    //observe the event
    public void fallbackOnServiceBFailure(@Observes @FailureMethod("serviceB") ExecutionFailureEvent events){
        
        //fallback method body
    }
}`

**Comment by Emily-Jiang** [comment]
Had a further thought on this. I think this event model does not address the fallback aspect on Hystrix and failsafe as that fallback approach is kind of treating fallback as part of mainservice invocation. This event model separates main service from fallback. I think it is still useful for logging and metrix gathering purpose. Thoughts?

**Comment by kenfinnigan** [comment]
After looking at the usage, it definitely looks like something that would be an implementation detail as opposed to developer created.

Right now I'm not sure what's provided would be beneficial for metrics/logging. It would require more investigation

**Comment by Emily-Jiang** [comment]
I think the event model is useful so that the status of circuit breaker etc can be logged and observed at a minimum. It is completely optional for the app developers.

**Comment by kenfinnigan** [comment]
I don't think there's a use case for a developer needing this ability, so I would consider this an implementation detail rather than something that's part of an exposed API

**Comment by heiko-braun** [comment]
I think fallback methods might require access to the invocation context. I.e what about possible parameters passed into `serviceA()` and `serviceB()`?

**Comment by heiko-braun** [comment]
Ah, I see it's part of `ExecutionFailureEvent`.

**Pull request closed without merging**
