### PR TITLE
Gordon tck max duration fix

### PR DESCRIPTION
**Pull request by hutchig**
With these all the bulkhead tests seem to pass reliably now for me so far.

### CODE REVIEW

**Comment by johnament** [comment]
What issue is this for?

**Comment by Emily-Jiang** [comment]
@hutchig Can you create an issue please, so that it is easier to track the changes?

**Comment by hutchig** [comment]
Apologies John, I am a bit of a newbie in open source development, I will raise an issue with a description of the problem.

**Comment by hutchig** [comment]
@Emily-Jiang @johnament  Are the above issues OK or is there more I can do?

**Comment by Emily-Jiang** [comment]
Thanks @hutchig !

**Pull request merged**
