### PR TITLE
#144 change the default maxDuration value to 1min

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by johnament** [comment]
if I have my maxRetries set to 3, does this meant he overall operation time is max'd at 60s?

**Comment by Emily-Jiang** [comment]
@johnament yes.

**Comment by Emily-Jiang** [comment]
I'm going to merge this one and start a RC3 release shortly.

**Comment by johnament** [comment]
the numbers don't make any sense.  if the default call for a single operation is 60s, the the overall default max can't be 60 * 3 = 60.

**Pull request merged**
