### PR TITLE
Fix TimeoutConfigTest bug

### LINKED ISSUE #563: TimeoutConfigTest bug
The following test:
https://github.com/eclipse/microprofile-fault-tolerance/blob/5fb645a732a29bc47b184a8e015e3ab843d99848/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/config/TimeoutConfigTest.java#L95

Fails with the following error: 
```
java.lang.NoClassDefFoundError: org.eclipse.microprofile.fault.tolerance.tck.asynchronous.CompletableFutureHelper
```

Since `CompletableFutureHelper.class` is not added to the test application.

### PR DESCRIPTION
**Pull request by Joseph-Cass**
Resolves #563

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by Ladicek** [comment]
What's more interesting is that I don't see the test failing for me :-)

**Comment by Azquelt** [comment]
Are you running with an embedded container that has all the test classes on the classpath?

**Comment by Ladicek** [comment]
Indeed that's what I do. Makes sense, thanks :-)

**Comment by Joseph-Cass** [comment]
> I'd add it to the previous line (`addClasses` accepts many classes), but that's just cosmetics.

Just done it :)

**Comment by Azquelt** [comment]
@genie-microprofile test this please

**Pull request merged**
