### PR TITLE
#174 update expected exception in tck to better align with spec

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by Pandrex247** [comment]
I think these tests need to be made more permissive, as they're assuming that an implementation isn't passing the exception to something else.
These tests are mandating that the final exception returned be `FaultToleranceDefinitionException`, which seems extremely strict - it's not checking any of the causes of the received exception at all.

**Comment by Emily-Jiang** [comment]
No. It does not mandate the final exception is `FaultToleranceDefinitionException`. It asserts this exception is in the chain. In your tck runner, you can check this exception on the chain. 

Have that said, as I mentioned on the call with @johnament and @antoinesd, it is better to catch CDI `DefinitionException`. In this way, we are certain all app servers throws the same top level exception as well instead of wrapping on a different exception. Please see #174 for more details.

I will close this PR if no objections.

**Comment by Pandrex247** [comment]
Hmm, if that's the case I'll have to debug Arquillian to see what it's getting back.
Checking our log file, we're throwing a deployment exception with a cause of `FaultToleranceDefinitionException`, yet Arquillian claims we're failing these tests.

**Comment by Pandrex247** [comment]
So the reason it's failing for us is because we're testing using a remote Arquillian container, which is using Rest to send the deploy command and receive the result. Since it's using Rest, it's just getting a failure response, not an exception, and so reading the response code and throwing a generic container exception to mark that something went wrong (Jersey's `ContainerException` in our case).

So the argument for making the test more permissive would be to accommodate remote containers using Rest.

**Comment by smillidge** [comment]
These deployment test don't work on remote arquillian profiles the Exception should be relaxed. As @Pandrex247 states we test using a remote arquillian profile which deploys via REST to a standalone server.

**Comment by Emily-Jiang** [comment]
Can you explain a bit more @smillidge ? You can code up the arquillian runner to search for a particular exception on the chain not the final exception, which is most of us doing.

**Comment by smillidge** [comment]
I'm not an arquillian expert but our Arquillian plugin uses the administration REST interface to deploy to a remote Payara Server. As the application fails to deploy (passing the test) we don't receive a full exception chain just a REST response saying the application failed to deploy.

**Comment by Emily-Jiang** [comment]
@smillidge you should be able to view the exception and find the expected exception from the stack. @hutchig has done a PR to arquillian for such a functionality.

**Comment by Emily-Jiang** [comment]
also @johnament and @McFoggy did further improvement in Arquillian to make it much easier for negative tests. @McFoggy will consume the latest version of Arquillian soon.

**Comment by smillidge** [comment]
I don't understand Arquillian enough to know which side the exception check is done on in the remote case. If it is on the server side then perhaps the exception can be extracted from the stack. If on the client side I don't see how this can be done given it is a REST call. I suspect it needs more investigation.

**Comment by McFoggy** [comment]
@Emily-Jiang let's be clear ; there are 2 issues for me behind the use of `@ShouldThrowException`:
- there was the problem that Arquillian didn't allow such a Deployment to be _testable_ (making arquillian extension not to be called); which was fixed & merged via @johnament PR arquillian/arquillian-core#135. For this I think that adapting the TCK using my [branch](https://github.com/McFoggy/microprofile-fault-tolerance/tree/issue-200) especially latest commit [83bffc54](https://github.com/McFoggy/microprofile-fault-tolerance/commit/83bffc54053addae283107a972229b73f8131890) will correct that behavior
- and there is the issue mentionned above by @Pandrex247 & @smillidge regarding the retrieval/encapsulation of deployment issues for remote containers. For wildfly, I opened yesterday wildfly/wildfly-arquillian#116 but other container adapters have the same problems.

The second bullet point is not easy to solve and depends on the adaptation of a lot of arquillian container adapters.

There might be other ways to check the deployment failure in Arquillian (including making use of the extension/plugin capabilities), but I don't know the library enough to show the good path.

**Comment by Emily-Jiang** [comment]
no longer needed.

**Pull request closed without merging**
