### PR TITLE
README.adoc: formatting fixes

### PR DESCRIPTION
**Pull request by ecki**
Fix broken formatting of usage header and use more consistent descriptions.

### CODE REVIEW

**Comment by ecki** [comment]
My ECA is signed here https://accounts.eclipse.org/users/beckenfels

**Comment by Emily-Jiang** [comment]
@ecki You need to sign off your commit using `git commit -s `. You might need to redo the PR.

**Comment by Azquelt** [comment]
I think the automation is complaining because the author e-mail of the commit doesn't match @ecki's eclipse account.

Clicking through to the details, it says `Anonymous (ecki@****.org) is not covered by the necessary legal agreements in order to proceed.`

**Comment by ecki** [comment]
I don’t want to use the email address associated with my eca and the eclipse infrastructure does not allow to specify multiple. You would need to manually approve that commit, as it’s a trivial change anyway.

**Comment by Emily-Jiang** [comment]
Sorry, unfortunately, we can't accept PRs without ECA signed off due to IP reasons. You can go ahead to close this PR off if you don't want to sign off the PR and just raise an issue to report the problems so that we can get it fixed.

**Comment by ecki** [comment]
You actually can, eclipse bylaw says the commited must check, it does not force you to use a bot. But nevermind, lets celebrate bouroacy.

**Pull request closed without merging**
